import { createClient } from '@supabase/supabase-js';
import './style.css';
const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_ANON_KEY,sb=U&&K?createClient(U,K):null;
const app=document.querySelector('#app');
const state={session:null,profile:null,week:weekStart(new Date()),tab:'dashboard',rows:[],classes:[],students:[],rules:[],locks:[]};
function weekStart(d){const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));x.setHours(0,0,0,0);return x.toISOString().slice(0,10)}
function weekEnd(){return new Date(new Date(state.week+'T00:00:00').getTime()+7*864e5).toISOString()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function role(){return state.profile?.role||'guest'}
function labelRole(){return ({red_team:'Cờ đỏ',homeroom:'GVCN',tpt:'TPT Đội',admin:'BGH / Quản trị'})[role()]||'Khách'}
function shell(){return `<header><div><b>TRƯỜNG TIỂU HỌC VÀ THCS THÁI TRỊ</b><small>xã Khánh Hưng, tỉnh Tây Ninh • 2026–2027</small></div>${state.session?`<span class="user">${esc(state.profile?.full_name||state.session.user.email)} · ${labelRole()} <button id="logout">Đăng xuất</button></span>`:''}</header><main>${state.session?`<nav>${nav('dashboard','Tổng quan')}${['red_team','tpt','admin'].includes(role())?nav('record','⚡ Ghi nhận'):''}${nav('history','Lịch sử')}${['tpt','admin'].includes(role())?nav('review','Duyệt'):''}${['tpt','admin'].includes(role())?nav('reports','Báo cáo'):''}${role()==='admin'?nav('manage','Quản trị'):''}</nav><section id="view"></section>`:`<section class="login"><h1>Quản lý nề nếp</h1><p>Đăng nhập tài khoản được nhà trường cấp.</p><input id="email" type="email" placeholder="Email"><input id="pass" type="password" placeholder="Mật khẩu"><button id="login" class="primary">Đăng nhập</button>${!sb?'<p class="warn">Chưa cấu hình Supabase. Sao chép .env.example thành .env.local.</p>':''}</section>`}</main>`}
function nav(k,t){return `<button class="nav ${state.tab===k?'on':''}" data-tab="${k}">${t}</button>`}
async function load(){if(!sb){render();return}const {data:{session}}=await sb.auth.getSession();state.session=session;if(session){const {data:p}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();state.profile=p;await refresh()}render();}
async function refresh(){if(!sb)return;const from=state.week+'T00:00:00+07:00';const {data:rows}=await sb.from('records').select('id,student_id,class_id,category,score,status,occurred_at,note,area,rule_id,recorded_by').gte('occurred_at',from).lt('occurred_at',weekEnd()).order('occurred_at',{ascending:false});state.rows=rows||[];const c=await sb.from('classes').select('*').order('grade').order('name');state.classes=c.data||[];const s=await sb.from('students').select('id,student_code,full_name,class_id,active').eq('active',true).order('full_name');state.students=s.data||[];const ru=await sb.from('score_rules').select('*').eq('active',true).order('category').order('name');state.rules=ru.data||[];const l=await sb.from('weekly_locks').select('id,week_start,class_id,locked_at').eq('week_start',state.week);state.locks=l.data||[];}
function dashboard(){const a=state.rows.filter(x=>x.status==='approved'),v=a.filter(x=>x.category==='violation'),g=a.filter(x=>x.category==='good_deed'),pending=state.rows.filter(x=>x.status==='pending');const scores=state.classes.map(c=>{const z=a.filter(x=>x.class_id===c.id);return {...c,score:100+z.reduce((n,x)=>n+Number(x.score||0),0),v:z.filter(x=>x.category==='violation').length,g:z.filter(x=>x.category==='good_deed').length}}).sort((x,y)=>y.score-x.score);return `<div class="bar"><div><h2>Tổng quan</h2><p>Tuần bắt đầu <b>${state.week}</b></p></div><input id="week" type="date" value="${state.week}"></div><div class="cards"><div><b>${a.length}</b><span>Đã duyệt</span></div><div><b>${v.length}</b><span>Vi phạm</span></div><div><b>${g.length}</b><span>Việc tốt</span></div><div><b>${pending.length}</b><span>Chờ duyệt</span></div></div><div class="panel"><h3>Xếp hạng lớp trong tuần</h3><table><thead><tr><th>#</th><th>Lớp</th><th>Điểm</th><th>⚠️</th><th>⭐</th><th>Trạng thái</th></tr></thead><tbody>${scores.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td><td><strong>${x.score.toFixed(1)}</strong></td><td>${x.v}</td><td>${x.g}</td><td>${state.locks.some(l=>l.class_id===x.id)?'🔒 Đã khóa':'Mở'}</td></tr>`).join('')}</tbody></table></div>`}
function record(){return `<div class="bar"><div><h2>⚡ Ghi nhận nhanh</h2><p>Cờ đỏ/TPT lập biên bản, TPT/BGH duyệt sau.</p></div></div><div class="grid"><label>Lớp<select id="class">${state.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Học sinh<select id="student"></select></label><label>Loại<select id="rule">${state.rules.map(r=>`<option value="${r.id}" data-cat="${r.category}" data-score="${r.points}">${r.category==='violation'?'⚠️':'⭐'} ${esc(r.name)} (${r.points>0?'+':''}${r.points})</option>`).join('')}</select></label><label>Khu vực<input id="area" placeholder="Sân trường, hành lang..."></label><label class="full">Ghi chú<textarea id="note" placeholder="Mô tả ngắn gọn, khách quan..."></textarea></label></div><button class="primary big" id="save">GỬI GHI NHẬN</button>`}
function fillStudents(){const cl=document.querySelector('#class'),st=document.querySelector('#student');if(!cl||!st)return;const list=state.students.filter(s=>s.class_id===cl.value);st.innerHTML=list.map(s=>`<option value="${s.id}">${esc(s.full_name)} — ${esc(s.student_code)}</option>`).join('')}
function history(){const rows=visibleRows();return `<div class="bar"><h2>Lịch sử tuần</h2><button id="csv">Xuất CSV</button></div><div class="panel"><table><thead><tr><th>Thời gian</th><th>Học sinh</th><th>Lớp</th><th>Loại</th><th>Điểm</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(x=>rowHtml(x)).join('')}</tbody></table></div>`}
function review(){const rows=state.rows.filter(x=>x.status==='pending');return `<div class="bar"><div><h2>Duyệt ghi nhận</h2><p>${rows.length} bản ghi đang chờ · tuần ${state.week}</p></div><div>${rows.length?'<button id="approveAll" class="primary">Duyệt tất cả</button>':''}</div></div><div class="panel"><table><thead><tr><th>Thời gian</th><th>Học sinh</th><th>Loại</th><th>Điểm</th><th>Ghi chú</th><th>Thao tác</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('vi-VN')}</td><td>${studentName(x)}</td><td>${x.category==='violation'?'⚠️ Vi phạm':'⭐ Việc tốt'}</td><td>${x.score>0?'+':''}${x.score}</td><td>${esc(x.note||x.area||'')}</td><td><button data-approve="${x.id}" class="ok">Duyệt</button> <button data-reject="${x.id}" class="danger">Từ chối</button></td></tr>`).join('')}</tbody></table></div>`}
function reports(){const a=state.rows.filter(x=>x.status==='approved');const scores=state.classes.map(c=>{const z=a.filter(x=>x.class_id===c.id);return {name:c.name,score:100+z.reduce((n,x)=>n+Number(x.score||0),0),v:z.filter(x=>x.category==='violation').length,g:z.filter(x=>x.category==='good_deed').length}}).sort((x,y)=>y.score-x.score);return `<div class="bar"><div><h2>Báo cáo tuần</h2><p>Tuần ${state.week}</p></div><div><button id="csv">CSV</button><button id="print">In / PDF</button></div></div><div class="report"><h3>TRƯỜNG TIỂU HỌC VÀ THCS THÁI TRỊ</h3><p>BÁO CÁO NỀ NẾP TUẦN ${state.week}</p>${scores.map((x,i)=>`<div class="r"><b>${i+1}. ${esc(x.name)}</b><span>${x.score.toFixed(1)} điểm</span><span>⚠️ ${x.v}</span><span>⭐ ${x.g}</span></div>`).join('')}</div>`}
function manage(){return `<h2>Quản trị</h2><div class="cards"><div><b>${state.classes.length}</b><span>Lớp</span></div><div><b>${state.students.length}</b><span>Học sinh đang học</span></div><div><b>${state.rules.length}</b><span>Quy tắc</span></div><div><b>${state.locks.length}</b><span>Lớp đã khóa tuần</span></div></div><div class="panel"><h3>Khóa / mở khóa tuần theo lớp</h3><p>Khóa tuần giúp ngăn thay đổi dữ liệu đã chốt.</p>${state.classes.map(c=>{const locked=state.locks.some(l=>l.class_id===c.id);return `<div class="lockrow"><b>${esc(c.name)}</b><span>${locked?'🔒 Đã khóa':'Mở'}</span>${locked?`<button data-unlock="${c.id}">Mở khóa</button>`:`<button data-lock="${c.id}" class="primary">Khóa tuần</button>`}</div>`}).join('')}</div>`}
function studentName(x){return state.students.find(s=>s.id===x.student_id)?.full_name||x.student_id}
function rowHtml(x){const c=state.classes.find(c=>c.id===x.class_id);return `<tr><td>${new Date(x.occurred_at).toLocaleString('vi-VN')}</td><td>${esc(studentName(x))}</td><td>${esc(c?.name||'')}</td><td>${x.category==='violation'?'⚠️':'⭐'}</td><td>${x.score>0?'+':''}${x.score}</td><td>${esc(x.status)}</td></tr>`}
function visibleRows(){if(role()==='homeroom'){return state.rows.filter(x=>state.classes.some(c=>c.id===x.class_id))}return state.rows}
function render(){app.innerHTML=shell();if(!state.session)return;const v=document.querySelector('#view');v.innerHTML=state.tab==='dashboard'?dashboard():state.tab==='record'?record():state.tab==='history'?history():state.tab==='review'?review():state.tab==='reports'?reports():manage();bind();if(state.tab==='record')fillStudents()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#logout')?.addEventListener('click',async()=>{await sb.auth.signOut();state.session=null;state.profile=null;render()});document.querySelector('#login')?.addEventListener('click',async()=>{const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#pass').value});if(error)alert(error.message);else await load()});document.querySelector('#week')?.addEventListener('change',async e=>{state.week=weekStart(new Date(e.target.value+'T00:00:00'));await refresh();render()});document.querySelector('#class')?.addEventListener('change',fillStudents);document.querySelector('#save')?.addEventListener('click',save);document.querySelector('#csv')?.addEventListener('click',csv);document.querySelector('#print')?.addEventListener('click',()=>window.print());document.querySelector('#approveAll')?.addEventListener('click',()=>reviewMany(true));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>reviewOne(b.dataset.approve,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reviewOne(b.dataset.reject,'rejected'));document.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>lockClass(b.dataset.lock));document.querySelectorAll('[data-unlock]').forEach(b=>b.onclick=()=>unlockClass(b.dataset.unlock))}
async function save(){const cl=document.querySelector('#class').value,st=document.querySelector('#student').value,r=document.querySelector('#rule').selectedOptions[0];if(!st)return alert('Lớp này chưa có học sinh.');if(state.locks.some(l=>l.class_id===cl))return alert('Tuần này đã khóa lớp.');const row={student_id:st,class_id:cl,rule_id:r.value,category:r.dataset.cat,score:Number(r.dataset.score),area:document.querySelector('#area').value,note:document.querySelector('#note').value,occurred_at:new Date().toISOString(),status:'pending',recorded_by:state.session.user.id};const dup=state.rows.some(x=>x.student_id===st&&x.rule_id===r.value&&x.status!=='cancelled');if(dup&&!confirm('Đã có ghi nhận cùng học sinh/nội dung trong tuần. Vẫn gửi?'))return;const {error}=await sb.from('records').insert(row);if(error)alert(error.message);else{await refresh();state.tab='history';render();alert('Đã gửi ghi nhận chờ duyệt.')}}
async function reviewOne(id,status){const {error}=await sb.from('records').update({status}).eq('id',id).eq('status','pending');if(error)alert(error.message);else{await refresh();render()}}
async function reviewMany(ok){const ids=state.rows.filter(x=>x.status==='pending').map(x=>x.id);if(!ids.length)return;const {error}=await sb.from('records').update({status:ok?'approved':'rejected'}).in('id',ids).eq('status','pending');if(error)alert(error.message);else{await refresh();render()}}
async function lockClass(id){if(!confirm('Khóa tuần cho lớp này? Sau khi khóa, bản ghi của lớp sẽ không thể sửa/xóa.'))return;const {error}=await sb.from('weekly_locks').insert({week_start:state.week,class_id:id,locked_by:state.session.user.id});if(error)alert(error.message);else{await refresh();render()}}
async function unlockClass(id){if(!confirm('Mở khóa tuần cho lớp này?'))return;const {error}=await sb.from('weekly_locks').delete().eq('week_start',state.week).eq('class_id',id);if(error)alert(error.message);else{await refresh();render()}}
function csv(){const rows=visibleRows(),h=['Thời gian','Học sinh','Lớp','Loại','Điểm','Trạng thái','Khu vực','Ghi chú'];const lines=[h,...rows.map(x=>{const c=state.classes.find(c=>c.id===x.class_id);return [new Date(x.occurred_at).toLocaleString('vi-VN'),studentName(x),c?.name||'',x.category,x.score,x.status,x.area||'',x.note||'']})].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bao-cao-ne-nep-${state.week}.csv`;a.click();URL.revokeObjectURL(a.href)}
load();
