import { createClient } from '@supabase/supabase-js';
import './style.css';
const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_ANON_KEY,sb=U&&K?createClient(U,K):null;
const app=document.querySelector('#app');
const state={session:null,profile:null,week:weekStart(new Date()),tab:'dashboard',rows:[],classes:[],students:[],rules:[],locks:[],filterClass:'',filterStatus:'',filterSearch:'',pendingCount:0,offlineMode:false,reportPeriod:'week',reportRows:[],reportThreshold:3};
state.offlineQueue=loadQueue();
let qrScanner=null;
function loadQueue(){try{return JSON.parse(localStorage.getItem('offlineQueue')||'[]')}catch{return []}}
function saveQueue(){try{localStorage.setItem('offlineQueue',JSON.stringify(state.offlineQueue))}catch{}}
function cacheSnapshot(){try{localStorage.setItem('cachedSnapshot',JSON.stringify({week:state.week,rows:state.rows,classes:state.classes,students:state.students,rules:state.rules,locks:state.locks,pendingCount:state.pendingCount,profile:state.profile}))}catch{}}
function loadSnapshot(){try{return JSON.parse(localStorage.getItem('cachedSnapshot')||'null')}catch{return null}}
function weekStart(d){const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));const y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),dd=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${dd}`}
function weekEnd(){return new Date(new Date(state.week+'T00:00:00').getTime()+7*864e5).toISOString()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function role(){return state.profile?.role||'guest'}
function labelRole(){return ({red_team:'Cờ đỏ',homeroom:'GVCN',tpt:'TPT Đội',admin:'BGH / Quản trị'})[role()]||'Khách'}
function daysSinceExport(){try{const t=localStorage.getItem('lastCsvExport');if(!t)return Infinity;return (Date.now()-Number(t))/86400000}catch{return Infinity}}
async function loadReport(){if(!sb)return;if(state.reportPeriod==='week'){state.reportRows=state.rows;return}let from;const now=new Date();if(state.reportPeriod==='month'){from=new Date(now.getFullYear(),now.getMonth(),1)}else{const y=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;from=new Date(y,8,5)}try{const {data}=await sb.from('records').select('id,student_id,class_id,category,score,status,occurred_at,rule_id,note,area').gte('occurred_at',from.toISOString()).order('occurred_at',{ascending:false});state.reportRows=data||[]}catch(err){state.reportRows=state.rows}}
function shell(){const badge=state.pendingCount>0?` <span style="background:#dc2626;color:#fff;border-radius:10px;padding:0 6px;margin-left:4px;font-size:12px">${state.pendingCount}</span>`:'';const off=!navigator.onLine,q=state.offlineQueue.length;const banner=(off||q)?`<div style="background:${off?'#fee2e2':'#fef3c7'};padding:8px 16px;text-align:center;font-size:14px">${off?'📴 Đang ngoại tuyến — dữ liệu hiển thị có thể chưa mới nhất. ':''}${q?`🕓 ${q} ghi nhận đang chờ gửi khi có mạng.`:''}</div>`:'';return `${banner}<header><div><b>TRƯỜNG TIỂU HỌC VÀ THCS THÁI TRỊ</b><small>xã Khánh Hưng, tỉnh Tây Ninh • 2026–2027</small></div>${state.session?`<span class="user">${esc(state.profile?.full_name||state.session.user.email)} · ${labelRole()} <button id="logout">Đăng xuất</button></span>`:''}</header><main>${state.session?`<nav>${nav('dashboard','Tổng quan')}${['red_team','tpt','admin'].includes(role())?nav('record','⚡ Ghi nhận'):''}${nav('history','Lịch sử')}${['tpt','admin'].includes(role())?nav('review',`Duyệt${badge}`):''}${['tpt','admin'].includes(role())?nav('reports','Báo cáo'):''}${role()==='admin'?nav('manage','Quản trị'):''}</nav><section id="view"></section>`:`<section class="login"><h1>Quản lý nề nếp</h1><p>Đăng nhập tài khoản được nhà trường cấp.</p><input id="email" type="email" placeholder="Email"><input id="pass" type="password" placeholder="Mật khẩu"><button id="login" class="primary">Đăng nhập</button>${!sb?'<p class="warn">Chưa cấu hình Supabase. Sao chép .env.example thành .env.local.</p>':''}</section>`}</main>`}
function nav(k,t){return `<button class="nav ${state.tab===k?'on':''}" data-tab="${k}">${t}</button>`}
async function load(){if(!sb){render();return}try{const {data:{session}}=await sb.auth.getSession();state.session=session;if(session){const {data:p}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();state.profile=p;await refresh()}}catch(err){try{const {data:{session}}=await sb.auth.getSession();state.session=session}catch{}const snap=loadSnapshot();if(snap){state.profile=snap.profile;state.rows=snap.rows;state.classes=snap.classes;state.students=snap.students;state.rules=snap.rules;state.locks=snap.locks;state.pendingCount=snap.pendingCount||0}state.offlineMode=true}render();flushQueue()}
async function refresh(){if(!sb)return;if(!navigator.onLine){const snap=loadSnapshot();if(snap){state.rows=snap.rows;state.classes=snap.classes;state.students=snap.students;state.rules=snap.rules;state.locks=snap.locks;state.pendingCount=snap.pendingCount||0}state.offlineMode=true;return}try{const from=state.week+'T00:00:00+07:00';const {data:rows}=await sb.from('records').select('id,student_id,class_id,category,score,status,occurred_at,note,area,rule_id,recorded_by,cancel_reason,undo_reason').gte('occurred_at',from).lt('occurred_at',weekEnd()).order('occurred_at',{ascending:false});state.rows=rows||[];const c=await sb.from('classes').select('*').order('grade').order('name');state.classes=c.data||[];const s=await sb.from('students').select('id,student_code,full_name,class_id,active,qr_token').eq('active',true).order('full_name');state.students=s.data||[];const ru=await sb.from('score_rules').select('*').eq('active',true).order('category').order('name');state.rules=ru.data||[];const l=await sb.from('weekly_locks').select('id,week_start,class_id,locked_at').eq('week_start',state.week);state.locks=l.data||[];if(['tpt','admin'].includes(role())){const {count}=await sb.from('records').select('id',{count:'exact',head:true}).eq('status','pending');state.pendingCount=count||0}else{state.pendingCount=0}state.offlineMode=false;cacheSnapshot()}catch(err){const snap=loadSnapshot();if(snap){state.rows=snap.rows;state.classes=snap.classes;state.students=snap.students;state.rules=snap.rules;state.locks=snap.locks;state.pendingCount=snap.pendingCount||0}state.offlineMode=true}}
function dashboard(){const a=state.rows.filter(x=>x.status==='approved'),v=a.filter(x=>x.category==='violation'),g=a.filter(x=>x.category==='good_deed'),pending=state.rows.filter(x=>x.status==='pending');const scores=state.classes.map(c=>{const z=a.filter(x=>x.class_id===c.id);return {...c,score:100+z.reduce((n,x)=>n+Number(x.score||0),0),v:z.filter(x=>x.category==='violation').length,g:z.filter(x=>x.category==='good_deed').length}}).sort((x,y)=>y.score-x.score);const showCsvReminder=['tpt','admin'].includes(role())&&daysSinceExport()>=7;const banner=showCsvReminder?`<div class="panel" style="border:1px solid #f59e0b;background:#fffbeb;padding:12px;margin-bottom:16px;display:flex;justify-content:space-between;align-items:center"><span>📦 Đã lâu chưa sao lưu dữ liệu ra CSV. Nên xuất file định kỳ để phòng sự cố.</span><button id="csvReminder" class="primary">Xuất CSV ngay</button></div>`:'';return `${banner}<div class="bar"><div><h2>Tổng quan</h2><p>Tuần bắt đầu <b>${state.week}</b></p></div><input id="week" type="date" value="${state.week}"></div><div class="cards"><div><b>${a.length}</b><span>Đã duyệt</span></div><div><b>${v.length}</b><span>Vi phạm</span></div><div><b>${g.length}</b><span>Việc tốt</span></div><div><b>${pending.length}</b><span>Chờ duyệt</span></div></div><div class="panel"><h3>Xếp hạng lớp trong tuần</h3><table><thead><tr><th>#</th><th>Lớp</th><th>Điểm</th><th>⚠️</th><th>⭐</th><th>Trạng thái</th></tr></thead><tbody>${scores.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td><td><strong>${x.score.toFixed(1)}</strong></td><td>${x.v}</td><td>${x.g}</td><td>${state.locks.some(l=>l.class_id===x.id)?'🔒 Đã khóa':'Mở'}</td></tr>`).join('')}</tbody></table></div>`}
function record(){return `<div class="bar"><div><h2>⚡ Ghi nhận nhanh</h2><p>Cờ đỏ/TPT lập biên bản, TPT/BGH duyệt sau.</p></div><div><button type="button" id="scanQR" class="primary">📷 Quét mã QR học sinh</button></div></div><div id="qr-reader" style="display:none;max-width:320px;margin-bottom:16px"></div><p id="qr-status" style="display:none;color:#14532d;font-weight:600"></p><div class="grid"><label>Lớp<select id="class">${state.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Học sinh<select id="student"></select></label><label>Loại<select id="rule">${state.rules.map(r=>`<option value="${r.id}" data-cat="${r.category}" data-score="${r.points}">${r.category==='violation'?'⚠️':'⭐'} ${esc(r.name)} (${r.points>0?'+':''}${r.points})</option>`).join('')}</select></label><label>Khu vực<input id="area" placeholder="Sân trường, hành lang..."></label><label class="full">Ghi chú<textarea id="note" placeholder="Mô tả ngắn gọn, khách quan..."></textarea></label></div><button class="primary big" id="save">GỬI GHI NHẬN</button>`}
function fillStudents(){const cl=document.querySelector('#class'),st=document.querySelector('#student');if(!cl||!st)return;const list=state.students.filter(s=>s.class_id===cl.value);st.innerHTML=list.map(s=>`<option value="${s.id}">${esc(s.full_name)} — ${esc(s.student_code)}</option>`).join('')}
function queueAsRows(){return state.offlineQueue.map(q=>({id:'local-'+q.localId,localId:q.localId,student_id:q.student_id,class_id:q.class_id,category:q.category,score:q.score,status:'queued',occurred_at:q.occurred_at,note:q.note,area:q.area,rule_id:q.rule_id,recorded_by:q.recorded_by,cancel_reason:null,undo_reason:null,queued:true}))}
function filteredRows(){let rows=visibleRows();if(state.filterClass)rows=rows.filter(x=>x.class_id===state.filterClass);if(state.filterStatus)rows=rows.filter(x=>x.status===state.filterStatus);if(state.filterSearch){const q=state.filterSearch.toLowerCase();rows=rows.filter(x=>studentName(x).toLowerCase().includes(q))}return rows}
function history(){const rows=filteredRows();return `<div class="bar"><h2>Lịch sử tuần</h2><button id="csv">Xuất CSV</button></div><div class="filters"><select id="fClass"><option value="">Tất cả lớp</option>${state.classes.map(c=>`<option value="${c.id}" ${state.filterClass===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><select id="fStatus"><option value="">Tất cả trạng thái</option><option value="pending" ${state.filterStatus==='pending'?'selected':''}>Chờ duyệt</option><option value="approved" ${state.filterStatus==='approved'?'selected':''}>Đã duyệt</option><option value="rejected" ${state.filterStatus==='rejected'?'selected':''}>Từ chối</option><option value="cancelled" ${state.filterStatus==='cancelled'?'selected':''}>Đã hủy</option><option value="queued" ${state.filterStatus==='queued'?'selected':''}>Chờ gửi (offline)</option></select><input id="fSearch" placeholder="Tìm tên học sinh..." value="${esc(state.filterSearch)}"></div><div class="panel"><table><thead><tr><th>Thời gian</th><th>Học sinh</th><th>Lớp</th><th>Loại</th><th>Nội dung</th><th>Điểm</th><th>Trạng thái</th><th>Lý do</th><th>Thao tác</th></tr></thead><tbody>${rows.map(x=>rowHtml(x)).join('')}</tbody></table></div>`}
function review(){const rows=state.rows.filter(x=>x.status==='pending');return `<div class="bar"><div><h2>Duyệt ghi nhận</h2><p>${rows.length} bản ghi đang chờ · tuần ${state.week}</p></div><div>${rows.length?'<button id="approveAll" class="primary">Duyệt tất cả</button>':''}</div></div><div class="panel"><table><thead><tr><th>Thời gian</th><th>Học sinh</th><th>Loại</th><th>Điểm</th><th>Ghi chú</th><th>Thao tác</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('vi-VN')}</td><td>${studentName(x)}</td><td>${x.category==='violation'?'⚠️ Vi phạm':'⭐ Việc tốt'}</td><td>${x.score>0?'+':''}${x.score}</td><td>${esc(x.note||x.area||'')}</td><td><button data-approve="${x.id}" class="ok">Duyệt</button> <button data-reject="${x.id}" class="danger">Từ chối</button></td></tr>`).join('')}</tbody></table></div>`}
function reports(){const src=state.reportRows.length?state.reportRows:state.rows;const a=src.filter(x=>x.status==='approved');const scores=state.classes.map(c=>{const z=a.filter(x=>x.class_id===c.id);return {name:c.name,score:100+z.reduce((n,x)=>n+Number(x.score||0),0),v:z.filter(x=>x.category==='violation').length,g:z.filter(x=>x.category==='good_deed').length}}).sort((x,y)=>y.score-x.score);const violations=a.filter(x=>x.category==='violation');const weekMap={};violations.forEach(x=>{const wk=weekStart(new Date(x.occurred_at));weekMap[wk]=(weekMap[wk]||0)+1});const weeks=Object.keys(weekMap).sort();const maxCount=Math.max(1,...Object.values(weekMap));const trendHtml=weeks.length?`<div class="panel"><h3>Xu hướng vi phạm theo tuần</h3><table><thead><tr><th>Tuần bắt đầu</th><th>Số vi phạm</th><th></th></tr></thead><tbody>${weeks.map(wk=>`<tr><td>${wk}</td><td>${weekMap[wk]}</td><td><div style="background:#f59e0b;height:14px;width:${Math.round(weekMap[wk]/maxCount*200)}px;border-radius:3px"></div></td></tr>`).join('')}</tbody></table></div>`:'';const counts={};violations.forEach(x=>{counts[x.student_id]=(counts[x.student_id]||0)+1});const freq=Object.entries(counts).filter(([id,c])=>c>=state.reportThreshold).map(([id,c])=>{const s=state.students.find(s=>s.id===id);const c2=state.classes.find(cl=>cl.id===s?.class_id);return {name:s?.full_name||id,cls:c2?.name||'',c}}).sort((x,y)=>y.c-x.c);const freqHtml=`<div class="panel"><h3>Học sinh vi phạm nhiều lần (≥ <span id="threshVal">${state.reportThreshold}</span> lần)</h3><div style="margin-bottom:8px">Ngưỡng: <input id="reportThreshold" type="number" min="1" value="${state.reportThreshold}" style="width:60px"></div>${freq.length?`<table><thead><tr><th>Học sinh</th><th>Lớp</th><th>Số lần vi phạm</th></tr></thead><tbody>${freq.map(f=>`<tr><td>${esc(f.name)}</td><td>${esc(f.cls)}</td><td>${f.c}</td></tr>`).join('')}</tbody></table>`:'<p>Không có học sinh nào đạt ngưỡng này trong khoảng thời gian đang xem.</p>'}</div>`;const periodLabel=state.reportPeriod==='week'?'Tuần hiện tại':state.reportPeriod==='month'?'Tháng này':'Từ đầu năm học';return `<div class="bar"><div><h2>Báo cáo</h2><p>${periodLabel}</p></div><div><select id="reportPeriod"><option value="week" ${state.reportPeriod==='week'?'selected':''}>Tuần hiện tại</option><option value="month" ${state.reportPeriod==='month'?'selected':''}>Tháng này</option><option value="year" ${state.reportPeriod==='year'?'selected':''}>Từ đầu năm học</option></select><button id="csvReport">Xuất CSV</button><button id="print">In / PDF</button></div></div><div class="report"><h3>TRƯỜNG TIỂU HỌC VÀ THCS THÁI TRỊ</h3><p>BÁO CÁO NỀ NẾP — ${periodLabel}</p>${scores.map((x,i)=>`<div class="r"><b>${i+1}. ${esc(x.name)}</b><span>${x.score.toFixed(1)} điểm</span><span>⚠️ ${x.v}</span><span>⭐ ${x.g}</span></div>`).join('')}</div>${trendHtml}${freqHtml}`}
function manage(){return `<h2>Quản trị</h2><div class="cards"><div><b>${state.classes.length}</b><span>Lớp</span></div><div><b>${state.students.length}</b><span>Học sinh đang học</span></div><div><b>${state.rules.length}</b><span>Quy tắc</span></div><div><b>${state.locks.length}</b><span>Lớp đã khóa tuần</span></div></div><div class="panel"><h3>Khóa / mở khóa tuần theo lớp</h3><p>Khóa tuần giúp ngăn thay đổi dữ liệu đã chốt.</p>${state.classes.map(c=>{const locked=state.locks.some(l=>l.class_id===c.id);return `<div class="lockrow"><b>${esc(c.name)}</b><span>${locked?'🔒 Đã khóa':'Mở'}</span>${locked?`<button data-unlock="${c.id}">Mở khóa</button>`:`<button data-lock="${c.id}" class="primary">Khóa tuần</button>`}</div>`}).join('')}</div>`}
function studentName(x){return state.students.find(s=>s.id===x.student_id)?.full_name||x.student_id}
function ruleName(x){return state.rules.find(r=>r.id===x.rule_id)?.name||''}
function canCancel(x){return role()==='red_team'&&x.status==='pending'&&x.recorded_by===state.session?.user?.id}
function canUndo(x){return ['tpt','admin'].includes(role())&&(x.status==='approved'||x.status==='rejected')}
function statusLabel(x){return x.status==='queued'?'🕓 Chờ gửi (offline)':esc(x.status)}
function rowHtml(x){const c=state.classes.find(c=>c.id===x.class_id);const ly=x.status==='cancelled'?x.cancel_reason:(x.undo_reason?`Hoàn tác: ${x.undo_reason}`:'');return `<tr><td>${new Date(x.occurred_at).toLocaleString('vi-VN')}</td><td>${esc(studentName(x))}</td><td>${esc(c?.name||'')}</td><td>${x.category==='violation'?'⚠️':'⭐'}</td><td>${esc(ruleName(x))}</td><td>${x.score>0?'+':''}${x.score}</td><td>${statusLabel(x)}</td><td>${esc(ly||'')}</td><td>${canCancel(x)?`<button data-cancel="${x.id}" class="danger">Hủy</button>`:''}${canUndo(x)?`<button data-undo="${x.id}" class="danger">Hoàn tác duyệt</button>`:''}${x.queued?`<button data-dequeue="${x.localId}" class="danger">Xóa khỏi hàng đợi</button>`:''}</td></tr>`}
function visibleRows(){let rows=state.rows;if(role()==='homeroom'){rows=rows.filter(x=>state.classes.some(c=>c.id===x.class_id))}return [...queueAsRows(),...rows]}
function render(){app.innerHTML=shell();if(!state.session){bind();return}const v=document.querySelector('#view');v.innerHTML=state.tab==='dashboard'?dashboard():state.tab==='record'?record():state.tab==='history'?history():state.tab==='review'?review():state.tab==='reports'?reports():manage();bind();if(state.tab==='record')fillStudents()}
function renderHistoryTable(){const tbody=document.querySelector('#view table tbody');if(!tbody)return;tbody.innerHTML=filteredRows().map(x=>rowHtml(x)).join('');bindRowActions()}
function bindRowActions(){document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelOne(b.dataset.cancel));document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>undoApprove(b.dataset.undo));document.querySelectorAll('[data-dequeue]').forEach(b=>b.onclick=()=>dequeueOne(b.dataset.dequeue))}
function stopQR(){if(qrScanner){qrScanner.stop().then(()=>{qrScanner.clear()}).catch(()=>{}).finally(()=>{qrScanner=null;const box=document.querySelector('#qr-reader');if(box){box.style.display='none';box.innerHTML=''}})}}
function onScanSuccess(code){const text=String(code).trim();const s=state.students.find(x=>x.qr_token===text)||state.students.find(x=>x.student_code===text);const status=document.querySelector('#qr-status');if(!s){if(status){status.style.display='block';status.style.color='#b91c1c';status.textContent='Không tìm thấy học sinh với mã: '+text}return}stopQR();const cl=document.querySelector('#class');if(cl){cl.value=s.class_id}fillStudents();const st=document.querySelector('#student');if(st){st.value=s.id}if(status){status.style.display='block';status.style.color='#14532d';status.textContent='Đã nhận diện: '+s.full_name}}
function startQR(){const box=document.querySelector('#qr-reader');if(!box)return;if(typeof Html5Qrcode==='undefined'){alert('Chưa tải được thư viện quét QR. Kiểm tra lại kết nối mạng.');return}box.style.display='block';box.innerHTML='';qrScanner=new Html5Qrcode('qr-reader');qrScanner.start({facingMode:'environment'},{fps:10,qrbox:250},onScanSuccess,()=>{}).catch(err=>{alert('Không mở được camera: '+err);box.style.display='none';qrScanner=null})}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{stopQR();state.tab=b.dataset.tab;if(state.tab==='reports'){loadReport().then(render)}else{render()}});document.querySelector('#logout')?.addEventListener('click',async()=>{stopQR();await sb.auth.signOut();state.session=null;state.profile=null;render()});document.querySelector('#login')?.addEventListener('click',async()=>{const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#pass').value});if(error)alert(error.message);else await load()});document.querySelector('#week')?.addEventListener('change',async e=>{state.week=weekStart(new Date(e.target.value+'T00:00:00'));await refresh();render()});document.querySelector('#class')?.addEventListener('change',fillStudents);document.querySelector('#save')?.addEventListener('click',save);document.querySelector('#scanQR')?.addEventListener('click',()=>{if(qrScanner){stopQR()}else{startQR()}});document.querySelector('#csv')?.addEventListener('click',csv);document.querySelector('#csvReminder')?.addEventListener('click',csv);document.querySelector('#csvReport')?.addEventListener('click',csvReport);document.querySelector('#print')?.addEventListener('click',()=>window.print());document.querySelector('#approveAll')?.addEventListener('click',()=>reviewMany(true));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>reviewOne(b.dataset.approve,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reviewOne(b.dataset.reject,'rejected'));document.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>lockClass(b.dataset.lock));document.querySelectorAll('[data-unlock]').forEach(b=>b.onclick=()=>unlockClass(b.dataset.unlock));document.querySelector('#fClass')?.addEventListener('change',e=>{state.filterClass=e.target.value;render()});document.querySelector('#fStatus')?.addEventListener('change',e=>{state.filterStatus=e.target.value;render()});document.querySelector('#fSearch')?.addEventListener('input',e=>{state.filterSearch=e.target.value;renderHistoryTable()});document.querySelector('#reportPeriod')?.addEventListener('change',async e=>{state.reportPeriod=e.target.value;await loadReport();render()});document.querySelector('#reportThreshold')?.addEventListener('input',e=>{state.reportThreshold=Number(e.target.value)||1;render()});bindRowActions()}
async function save(){const cl=document.querySelector('#class').value,st=document.querySelector('#student').value,r=document.querySelector('#rule').selectedOptions[0];if(!st)return alert('Lớp này chưa có học sinh.');if(state.locks.some(l=>l.class_id===cl))return alert('Tuần này đã khóa lớp.');const row={student_id:st,class_id:cl,rule_id:r.value,category:r.dataset.cat,score:Number(r.dataset.score),area:document.querySelector('#area').value,note:document.querySelector('#note').value,occurred_at:new Date().toISOString(),status:'pending',recorded_by:state.session.user.id};const dup=visibleRows().some(x=>x.student_id===st&&x.rule_id===r.value&&x.status!=='cancelled');if(dup&&!confirm('Đã có ghi nhận cùng học sinh/nội dung trong tuần. Vẫn gửi?'))return;if(!navigator.onLine){queueRecord(row);return}try{const {error}=await sb.from('records').insert(row);if(error){if(error.code==='23505'){alert('Đã có người khác vừa ghi nhận trùng học sinh + nội dung này trong tuần. Vui lòng kiểm tra lại ở Lịch sử.')}else{alert(error.message)}}else{await refresh();state.tab='history';render();alert('Đã gửi ghi nhận chờ duyệt.')}}catch(err){queueRecord(row)}}
function queueRecord(row){const localId=Date.now()+'-'+Math.random().toString(36).slice(2,8);state.offlineQueue.push({...row,localId});saveQueue();state.tab='history';render();alert('Không có mạng — đã lưu tạm trên máy, sẽ tự gửi khi có mạng lại.')}
function dequeueOne(localId){if(!confirm('Xóa ghi nhận đang chờ gửi này khỏi hàng đợi?'))return;state.offlineQueue=state.offlineQueue.filter(q=>String(q.localId)!==String(localId));saveQueue();render()}
async function flushQueue(){if(!state.offlineQueue.length||!navigator.onLine)return;const remaining=[];for(const q of state.offlineQueue){const {localId,...row}=q;try{const {error}=await sb.from('records').insert(row);if(error)remaining.push(q)}catch(err){remaining.push(q)}}state.offlineQueue=remaining;saveQueue();await refresh();render()}
async function reviewOne(id,status){try{const {error}=await sb.from('records').update({status}).eq('id',id).eq('status','pending');if(error)alert(error.message);else{await refresh();render()}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
async function reviewMany(ok){const ids=state.rows.filter(x=>x.status==='pending').map(x=>x.id);if(!ids.length)return;try{const {error}=await sb.from('records').update({status:ok?'approved':'rejected'}).in('id',ids).eq('status','pending');if(error)alert(error.message);else{await refresh();render()}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
async function cancelOne(id){const reason=prompt('Lý do hủy ghi nhận (VD: Ghi nhầm học sinh, chọn nhầm lớp, ghi trùng...)');if(reason===null)return;try{const {error}=await sb.from('records').update({status:'cancelled',cancel_reason:reason||null,cancelled_at:new Date().toISOString()}).eq('id',id).eq('status','pending');if(error)alert(error.message);else{await refresh();render();alert('Đã hủy ghi nhận.')}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
async function undoApprove(id){const reason=prompt('Lý do hoàn tác duyệt (VD: Duyệt nhầm, cần xem lại, học sinh khiếu nại...)');if(reason===null)return;try{const {error}=await sb.from('records').update({status:'pending',undo_reason:reason||null,undone_by:state.session.user.id,undone_at:new Date().toISOString()}).eq('id',id).in('status',['approved','rejected']);if(error)alert(error.message);else{await refresh();render();alert('Đã hoàn tác, bản ghi quay về Chờ duyệt.')}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
async function lockClass(id){if(!confirm('Khóa tuần cho lớp này? Sau khi khóa, bản ghi của lớp sẽ không thể sửa/xóa.'))return;try{const {error}=await sb.from('weekly_locks').insert({week_start:state.week,class_id:id,locked_by:state.session.user.id});if(error)alert(error.message);else{await refresh();render()}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
async function unlockClass(id){if(!confirm('Mở khóa tuần cho lớp này?'))return;try{const {error}=await sb.from('weekly_locks').delete().eq('week_start',state.week).eq('class_id',id);if(error)alert(error.message);else{await refresh();render()}}catch(err){alert('Không có mạng, thử lại khi có kết nối.')}}
function csv(){const rows=filteredRows(),h=['Thời gian','Học sinh','Lớp','Loại','Nội dung','Điểm','Trạng thái','Khu vực','Ghi chú'];const lines=[h,...rows.map(x=>{const c=state.classes.find(c=>c.id===x.class_id);return [new Date(x.occurred_at).toLocaleString('vi-VN'),studentName(x),c?.name||'',x.category,ruleName(x),x.score,x.status,x.area||'',x.note||'']})].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bao-cao-ne-nep-${state.week}.csv`;a.click();URL.revokeObjectURL(a.href);try{localStorage.setItem('lastCsvExport',String(Date.now()))}catch{}}
function csvReport(){const rows=state.reportRows.length?state.reportRows:state.rows,h=['Thời gian','Học sinh','Lớp','Loại','Nội dung','Điểm','Trạng thái','Khu vực','Ghi chú'];const lines=[h,...rows.map(x=>{const c=state.classes.find(c=>c.id===x.class_id);return [new Date(x.occurred_at).toLocaleString('vi-VN'),studentName(x),c?.name||'',x.category,ruleName(x),x.score,x.status,x.area||'',x.note||'']})].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');const label=state.reportPeriod==='week'?state.week:state.reportPeriod==='month'?new Date().toISOString().slice(0,7):'nam-hoc';a.href=URL.createObjectURL(blob);a.download=`bao-cao-${label}.csv`;a.click();URL.revokeObjectURL(a.href);try{localStorage.setItem('lastCsvExport',String(Date.now()))}catch{}}
window.addEventListener('online',()=>{flushQueue()});
window.addEventListener('offline',()=>{render()});
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}
load();
